<?php

declare(strict_types=1);

namespace Mlevent\Fatura\Enums;

enum Currency: string
{
    case AFN = 'AFN';
    case DZD = 'DZD';
    case ARS = 'ARS';
    case AWG = 'AWG';
    case AUD = 'AUD';
    case AZM = 'AZM';
    case BSD = 'BSD';
    case BHD = 'BHD';
    case THB = 'THB';
    case PAB = 'PAB';
    case BBD = 'BBD';
    case BYR = 'BYR';
    case BZD = 'BZD';
    case BMD = 'BMD';
    case VEB = 'VEB';
    case BOB = 'BOB';
    case BGN = 'BGN';
    case BRL = 'BRL';
    case BND = 'BND';
    case BIF = 'BIF';
    case CAD = 'CAD';
    case CVE = 'CVE';
    case KYD = 'KYD';
    case GHC = 'GHC';
    case XAF = 'XAF';
    case XPF = 'XPF';
    case CLP = 'CLP';
    case COP = 'COP';
    case KMF = 'KMF';
    case NIO = 'NIO';
    case CRC = 'CRC';
    case CUP = 'CUP';
    case CYP = 'CYP';
    case CZK = 'CZK';
    case DKK = 'DKK';
    case GMD = 'GMD';
    case MKD = 'MKD';
    case AED = 'AED';
    case DJF = 'DJF';
    case STD = 'STD';
    case DOP = 'DOP';
    case VND = 'VND';
    case AMD = 'AMD';
    case XCD = 'XCD';
    case EGP = 'EGP';
    case SVC = 'SVC';
    case ETB = 'ETB';
    case EUR = 'EUR';
    case FKP = 'FKP';
    case FJD = 'FJD';
    case HUF = 'HUF';
    case CDF = 'CDF';
    case GIP = 'GIP';
    case XAU = 'XAU';
    case HTG = 'HTG';
    case PYG = 'PYG';
    case GNF = 'GNF';
    case GYD = 'GYD';
    case HKD = 'HKD';
    case UAH = 'UAH';
    case ISK = 'ISK';
    case INR = 'INR';
    case IQD = 'IQD';
    case IRR = 'IRR';
    case JMD = 'JMD';
    case JOD = 'JOD';
    case KES = 'KES';
    case PGK = 'PGK';
    case LAK = 'LAK';
    case EEK = 'EEK';
    case HRK = 'HRK';
    case KWD = 'KWD';
    case MWK = 'MWK';
    case AOA = 'AOA';
    case MMK = 'MMK';
    case GEL = 'GEL';
    case LVL = 'LVL';
    case LBP = 'LBP';
    case ALL = 'ALL';
    case HNL = 'HNL';
    case SLL = 'SLL';
    case ROL = 'ROL';
    case LRD = 'LRD';
    case LYD = 'LYD';
    case SZL = 'SZL';
    case LTL = 'LTL';
    case LSL = 'LSL';
    case MGF = 'MGF';
    case MYR = 'MYR';
    case MTL = 'MTL';
    case TMM = 'TMM';
    case MUR = 'MUR';
    case MZM = 'MZM';
    case MXN = 'MXN';
    case MDL = 'MDL';
    case MAD = 'MAD';
    case NGN = 'NGN';
    case ERN = 'ERN';
    case NAD = 'NAD';
    case NPR = 'NPR';
    case ANG = 'ANG';
    case YUM = 'YUM';
    case ILS = 'ILS';
    case TWD = 'TWD';
    case NZD = 'NZD';
    case KPW = 'KPW';
    case NOK = 'NOK';
    case BTN = 'BTN';
    case PEN = 'PEN';
    case MRO = 'MRO';
    case TOP = 'TOP';
    case PKR = 'PKR';
    case XPD = 'XPD';
    case MOP = 'MOP';
    case UYU = 'UYU';
    case PHP = 'PHP';
    case XPT = 'XPT';
    case GBP = 'GBP';
    case BWP = 'BWP';
    case QAR = 'QAR';
    case GTQ = 'GTQ';
    case ZAR = 'ZAR';
    case OMR = 'OMR';
    case KHR = 'KHR';
    case MVR = 'MVR';
    case RON = 'RON';
    case IDR = 'IDR';
    case RUB = 'RUB';
    case RWF = 'RWF';
    case SAR = 'SAR';
    case XDR = 'XDR';
    case SCR = 'SCR';
    case XAG = 'XAG';
    case SGD = 'SGD';
    case SKK = 'SKK';
    case SBD = 'SBD';
    case SOS = 'SOS';
    case LKR = 'LKR';
    case KGS = 'KGS';
    case TJS = 'TJS';
    case SHP = 'SHP';
    case SDD = 'SDD';
    case SRG = 'SRG';
    case SEK = 'SEK';
    case CHF = 'CHF';
    case SYP = 'SYP';
    case BDT = 'BDT';
    case WST = 'WST';
    case TZS = 'TZS';
    case KZT = 'KZT';
    case SIT = 'SIT';
    case TTD = 'TTD';
    case MNT = 'MNT';
    case TND = 'TND';
    case TRY = 'TRY';
    case UGX = 'UGX';
    case USD = 'USD';
    case UZS = 'UZS';
    case VUV = 'VUV';
    case KRW = 'KRW';
    case YER = 'YER';
    case JPY = 'JPY';
    case CNY = 'CNY';
    case ZWD = 'ZWD';
    case PLN = 'PLN';

    /**
     * alias
     *
     * @return string
     */
    public function alias(): string
    {
        return match ($this) {
            self::AFN => 'Afghani',
            self::DZD => 'Algerian Dinar',
            self::ARS => 'Argentine Peso',
            self::AWG => 'Aruban Guilder',
            self::AUD => 'Australian Dollar',
            self::AZM => 'Azerbaijanian Manat',
            self::BSD => 'Bahamian Dollar',
            self::BHD => 'Bahraini Dinar',
            self::THB => 'Baht',
            self::PAB => 'Balboa',
            self::BBD => 'Barbados Dollar',
            self::BYR => 'Belarussian Ruble',
            self::BZD => 'Belize Dollar',
            self::BMD => 'Bermudian Dollar',
            self::VEB => 'Bolivar',
            self::BOB => 'Boliviano',
            self::BGN => 'Bulgarian Lev',
            self::BRL => 'Brazilian Real',
            self::BND => 'Brunei Dollar',
            self::BIF => 'Burundi Franc',
            self::CAD => 'Canadian Dollar',
            self::CVE => 'Cape Verde Escudo',
            self::KYD => 'Cayman Islands Dollar',
            self::GHC => 'Cedi',
            self::XAF => 'CFA Franc',
            self::XPF => 'CFP Franc',
            self::CLP => 'Chilean Peso',
            self::COP => 'Colombian Peso',
            self::KMF => 'Comoro Franc',
            self::NIO => 'Cordoba Oro',
            self::CRC => 'Costa Rican Colon',
            self::CUP => 'Cuban Peso',
            self::CYP => 'Cyprus Pound',
            self::CZK => 'Czech Koruna',
            self::DKK => 'Danish Krone',
            self::GMD => 'Dalasi',
            self::MKD => 'Denar',
            self::AED => 'Dirham',
            self::DJF => 'Djibouti Franc',
            self::STD => 'Dobra',
            self::DOP => 'Dominican Peso',
            self::VND => 'Dong',
            self::AMD => 'Dram',
            self::XCD => 'East Carribean Dollar',
            self::EGP => 'Egyptian Pound',
            self::SVC => 'El Salvador Colon',
            self::ETB => 'Ethopian Birr',
            self::EUR => 'Euro',
            self::FKP => 'Falkland Islands Pound',
            self::FJD => 'Fiji Dollar',
            self::HUF => 'Forint',
            self::CDF => 'Franc Congolais',
            self::GIP => 'Gibraltar Pound',
            self::XAU => 'Gold',
            self::HTG => 'Gourde',
            self::PYG => 'Guarani',
            self::GNF => 'Guinea Franc',
            self::GYD => 'Guyana Dollar',
            self::HKD => 'HKD',
            self::UAH => 'Hryvnia',
            self::ISK => 'Iceland Krona',
            self::INR => 'Indian Rupee',
            self::IQD => 'Iraqi Dinar',
            self::IRR => 'Iranian Rial',
            self::JMD => 'Jamaican Dollar',
            self::JOD => 'Jordanian Dinar',
            self::KES => 'Kenyan Shilling',
            self::PGK => 'Kina',
            self::LAK => 'Kip',
            self::EEK => 'Kroon',
            self::HRK => 'Kuna',
            self::KWD => 'Kuwaiti Dinar',
            self::MWK => 'Kwacha',
            self::AOA => 'Kwanza',
            self::MMK => 'Kyat',
            self::GEL => 'Lari',
            self::LVL => 'Latvian Lats',
            self::LBP => 'Lebanese Pound',
            self::ALL => 'Lek',
            self::HNL => 'Lempira',
            self::SLL => 'Leone',
            self::ROL => 'Leu',
            self::LRD => 'Liberian Dollar',
            self::LYD => 'Libyan Dinar',
            self::SZL => 'Lilangeni',
            self::LTL => 'Lithuanian Litas',
            self::LSL => 'Loti',
            self::MGF => 'Malagasy Franc',
            self::MYR => 'Malaysian Ringgit',
            self::MTL => 'Maltese Lira',
            self::TMM => 'Manat',
            self::MUR => 'Mauritius Rupee',
            self::MZM => 'Metical',
            self::MXN => 'Mexican Peso',
            self::MDL => 'Moldovan Leu',
            self::MAD => 'Morrocan Dirham',
            self::NGN => 'Naira',
            self::ERN => 'Nakfa',
            self::NAD => 'Namibia Dollar',
            self::NPR => 'Nepalese Rupee',
            self::ANG => 'Netherlands Antillian Guilder',
            self::YUM => 'New Dinar',
            self::ILS => 'New Israeli Sheqel',
            self::TWD => 'New Taiwan Dollar',
            self::NZD => 'New Zealand Dollar',
            self::KPW => 'North Korean Won',
            self::NOK => 'Norwegian Krone',
            self::BTN => 'Ngultrum',
            self::PEN => 'Nuevo Sol',
            self::MRO => 'Ouguiya',
            self::TOP => 'Pa&apos;anga',
            self::PKR => 'Pakistan Rupee',
            self::XPD => 'Palladium',
            self::MOP => 'Pataca',
            self::UYU => 'Peso Uruguayo',
            self::PHP => 'Philippine Peso',
            self::XPT => 'Platinum',
            self::GBP => 'Pound Sterling',
            self::BWP => 'Pula',
            self::QAR => 'Qatari Rial',
            self::GTQ => 'Quetzal',
            self::ZAR => 'Rand',
            self::OMR => 'Rial Omani',
            self::KHR => 'Riel',
            self::MVR => 'Rufiyaa',
            self::RON => 'Rumen Leyi',
            self::IDR => 'Rupiah',
            self::RUB => 'Russian Ruble',
            self::RWF => 'Rwanda Franc',
            self::SAR => 'Saudi Riyal',
            self::XDR => 'SDR',
            self::SCR => 'Seychelles Rupee',
            self::XAG => 'Silver',
            self::SGD => 'Singapore Dollar',
            self::SKK => 'Slovak Koruna',
            self::SBD => 'Solomon Islands Dollar',
            self::SOS => 'Somali Shilling',
            self::LKR => 'Sri Lanka Rupee',
            self::KGS => 'Som',
            self::TJS => 'Somoni',
            self::SHP => 'St. Helena Pound',
            self::SDD => 'Sudanese Dinar',
            self::SRG => 'Suriname Guilder',
            self::SEK => 'Swedish Krona',
            self::CHF => 'Swiss Franc',
            self::SYP => 'Syrian Pound',
            self::BDT => 'Taka',
            self::WST => 'Tala',
            self::TZS => 'Tanzanian Shilling',
            self::KZT => 'Tenge',
            self::SIT => 'Tolar',
            self::TTD => 'Trinidad and Tobago Dollar',
            self::MNT => 'Tugrik',
            self::TND => 'Tunisian Dinar',
            self::TRY => 'Turkish Lira',
            self::UGX => 'Uganda Shilling',
            self::USD => 'American Dollar',
            self::UZS => 'Uzbekistan Sum',
            self::VUV => 'Vatu',
            self::KRW => 'Won',
            self::YER => 'Yemeni Rial',
            self::JPY => 'Yen',
            self::CNY => 'Yuan Renminbi',
            self::ZWD => 'Zimbabwe Dollar',
            self::PLN => 'Zloty',
        };
    }
}